service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-south-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: fertilizersModel
    handler: lambda.handler
    description: fertilizersModel
    timeout: 10 # seconds
    memorySize: 256 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"