name: Deploy lambda 

on:
  push:
    branches:
      - fertilisers-lambda-function

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: denzalman/lambda-python-action@v2.0.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:ap-south-1:780431747353:layer:fertilizerDependencyLayer'
        lambda_function_name: 'fertilizersModel'
        lambda_region: 'ap-south-1'
        requirements_txt: 'requirements.txt'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}