name: Update AWS Lambda Function

on:
  push:
    branches:
      - fertilisers-lambda-function

jobs:
  update:
    runs-on: fertilisers-lambda-function

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python3.9 -m pip install -r requirements.txt

      - uses: actions/checkout@v2
      - uses: rotarydialer/update-lambda-s3@main
        env:
          LAMBDA_NAME: fertilizersModel
          AWS_S3_BUCKET: fertilizerbucket
          AWS_S3_KEY: builds/example-lambda.v1.0.0.zip
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
