on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy code to Lambda
        uses: qubitro/action-lambda-python-zip@v1.0
        with:
          lambda_layer_arn: "arn:aws:lambda:eu-central-1:222222222222:layer:layer-name"
          lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          lambda_region: "eu-central-1"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
