on:
  push:
    branches:
      - fertilisers-lambda-function
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy code to Lambda
        uses: qubitro/action-lambda-python-zip@v1.0
        with:
          lambda_layer_arn: "arn:aws:lambda:ap-south-1:780431747353:function:fertilizersModel"
          lambda_function_name: fertilizersModel
          lambda_region: "ap-south-1"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
